services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: software-suite-backend
    ports:
      - 8085:8085
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: postgres
      DATABASE_PORT: ${DATABASE_PORT}
    networks:
      - software_suite

networks:
  software_suite:
    driver: bridge
    external: true
