services:
  grafana:
    image: docker.arvancloud.ir/grafana/grafana:11.0.0
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - software_suite
    ports:
      - 3030:3000

volumes:
  grafana_data:

networks:
  software_suite:
    driver: bridge
    external: true
