services:
  gitlab:
    image: docker.arvancloud.ir/gitlab/gitlab-ce:latest
    container_name: gitlab
    ports:
      - 8088:80
    environment:
      GITLAB_ROOT_EMAIL: ${GITLAB_ROOT_EMAIL}
      GITLAB_ROOT_PASSWORD: ${GITLAB_ROOT_PASSWORD}
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_data:/var/opt/gitlab
    networks:
      - software_suite

volumes:
  gitlab_config:
  gitlab_data:

networks:
  software_suite:
    driver: bridge