services:
  nexus:
    image: docker.arvancloud.ir/sonatype/nexus3:3.87.1-alpine
    container_name: nexus
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
    networks:
      - software_suite

volumes:
  nexus_data:

networks:
  software_suite:
    driver: bridge
    external: true
